echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27" 
echo "I am learning Git/Github"
echo "I have added new code"
echo "This is the last line of code"
echo "Adding one more line to check git status"